
package ink.z31.liverprotector.bean.pveGetPveData;
import java.util.List;
public class PveLevel {
    public String id;
    public String title;
    public String type;
    public String difficulty;
    public String need_pve_levels;
    public String award;
    public String user_exp;
    public String boss_user_exp;
    public String ship_exp;
    public String boss_ship_exp;
    public String boss_bg;
    public String hp;
    public String hp2;
    public String hp_type;
    public String next_pve_id;
    public String next_pve_level;
    public String task_cid;
    public String isRedPath;
    public String desc;
    public String position;
    public String arrow;
    public String is_support;
    public String support_pre_desc;
    public String support_next_desc;
    public String support_id;
    public String support_open_desc;
    public String fleet_type;
    public String sup_attack;
    public List<String> need_ship_ton;
    public String need_ship_ton_desc;
    public String ship_ton_desc;
    public String animation;
    public String music;
    public String initNodeId;
    public String nodeNum;
    public List<String> pruductGoods;
    public String pveId;
    public int bossId;
    public int mapId;
    public String needPveLevelId;
    public String subTitle;
    public String needUserLevel;
}