
package ink.z31.liverprotector.bean.apiInitGame;
import java.util.List;
public class UserShipVO {
    public int id;
    public long uid;
    public String title;
    public int level;
    public int exp;
    public int energy;
    public int max_ammo;
    public String missile_slot;
    public int fleet_id;
    public int status;
    public int sink_num;
    public String skin_cid;
    public int fight_num;
    public long hurt_ship_num;
    public int sink_ship_num;
    public String miss_num;
    public String pvp_win_num;
    public String repair_num;
    public int ammo_num;
    public int steel_num;
    public int oil_num;
    public int aluminium_num;
    public String marry_time;
    public String build_boat_num;
    public String team_medal;
    public List<String> active_medal;
    public List<String> cookbook;
    public Tactics tactics;
    public String create_time;
    public int type;
    public long nextExp;
    public int married;
    public int love;
    public int loveMax;
    public int ammoSlot;
    public long shipCid;
    public StrengthenAttribute strengthenAttribute;
    public int fleetId;
    public int isLocked;
    public List<Integer> capacitySlot;
    public List<Integer> capacitySlotMax;
    public List<Integer> capacitySlotExist;
    public List<Integer> missileSlot;
    public List<Integer> missileSlotMax;
    public List<Integer> missileSlotExist;
    public List<String> equipmentArr;
    public int use_equipment;
    public BattlePropsBasic battlePropsBasic;
    public BattleProps battleProps;
    public BattlePropsMax battlePropsMax;
}